services:
  postgres:
    image: postgres:17
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: distributed-url-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

