CREATE TABLE url_click_analytics (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     url_id BIGINT NOT NULL,
                                     short_code VARCHAR(20) NOT NULL,
                                     clicked_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                     processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_url_click_analytics_url_id
    ON url_click_analytics(url_id);

CREATE INDEX idx_url_click_analytics_short_code
    ON url_click_analytics(short_code);

CREATE INDEX idx_url_click_analytics_clicked_at
    ON url_click_analytics(clicked_at);